### ISSUE TITLE
Imaging Source

### ISSUE THREAD

**Issue by ichristen** [slmsuite/slmsuite#25]
Write a [Imaging Source](https://www.theimagingsource.com/) camera interface via [tisgrabber](https://github.com/TheImagingSource/IC-Imaging-Control-Samples/tree/master/Python).

**Comment by kwang428** [comment]
Hi, I am working on an interface to a Imaging Source camera via `tisgrabber`. I just wanted to check with how I should deal with error handling? How does `slmsuite` in general respond to errors from the camera? Should my class never throw an error, or are the errors handled by callers?

**Comment by ichristen** [comment]
Hi @kwang428 ,

Awesome! Thank you for tackling this. `slmsuite` does not respond to errors from the camera (no try/except anywhere). You should throw errors, especially in the constructor, as the user will find this information useful.

The one place that you might consider _not_ throwing an error is in `.get_image()`, because frame grabbing is often not 100% reliable and taking thousands of frames leads to a larger probability of hitting a small per frame chance of failure. In other cameras, if an error occurs or the framebuffer is not filled, the behavior is to try to get an image again such a long experiment is not stalled by a rare failure. We'll probably be looking to polish this behavior and move it to the abstract class or something, but in the meantime you should consider just not throwing an error.

Thanks again!

Best,
Ian
