### ISSUE TITLE
DataRay Camera support

### ISSUE THREAD

**Issue by dwgong** [slmsuite/slmsuite#51]
Hi,

We really like you package. But we are using a lot of DataRay cameras in the lab. So I'm wondering if it's possible that you can support it in the future

**Comment by ichristen** [comment]
Hi @dwgong ,

Glad to hear the package is useful!

Contributions to add new hardware are welcome! There are a few ways we could go about this:

- You could send us sample code for what you've been using to connect to DataRay cameras and we can format it as an `slmsuite.hardware.camera`. [This](https://github.com/QPG-MIT/slmsuite/blob/main/slmsuite/hardware/cameras/template.py) is a `template` for what abstract methods need to be filled to get a functional camera interface.
- You can format the above and send it to us for review via GitHub pull request.

Whatever the case, it would be good to test the code on hardware before adding it to `main`. We unfortunately do not have any DataRay cameras and thus cannot test on hardware ourselves.

Best,
Ian

**Comment by ichristen** [comment]
Hi @dwgong 

I was looking more into the DataRay interface in preparation for r0.0.3. It seems that the standard interface for DataRay (from what I found in a quick search) is to use ActiveX, which is concerning to me:

- Uses wx ActiveX https://dataray.com/resources/interfacing
- Uses Qt ActiveX https://github.com/sunjerry019/nanosquared/blob/master/src/nanosquared/cameras/wincamd.py

What interface do you currently use for your cameras? I'm skeptical about adding an ActiveX interface to slmsuite, but would be more open if there was a .dll option. Is there still interest in adding DataRay support?

Best,
Ian

**Comment by ichristen** [comment]
Decided to not pursue this interface. Let us know if there's interest.
