### ISSUE TITLE
Allied Vision Vimba-X Support

### ISSUE THREAD

**Issue by tpr0p** [slmsuite/slmsuite#66]
Allied Vision has released a new SDK called "Vimba X". It uses `vmbpy` as opposed to the earlier "Vimba" SDK which had the `vimba` module.
https://www.alliedvision.com/en/products/software/vimba-x-sdk/

**Comment by ichristen** [comment]
I think we probably won't pursue this. The site you linked hints at support for Windows 10+, and I would like to maintain support for older versions of Windows. The new features that Vimba-X do not seem applicable to our needs. I would suggest that we only move to Vimba-X if 1) Vimba loses support, or 2) it is clear that Vimba-X is more stable than Vimba.

**Comment by ichristen** [comment]
I changed my mind. We should upgrade next release.

**Comment by ichristen** [comment]
#81 and #83 implement this.
