### ISSUE TITLE
pyglet 2.0.0

### ISSUE THREAD

**Issue by tpr0p** [slmsuite/slmsuite#7]
pyglet updated to 2.0.0 on 11/01/2022 which caused breaking changes for screen-mirrored slms. We should find a stable way to version the package's dependencies. See about doing this in `setup.py`, which notes dependencies for `pip install git+<>`. Also we should fix the screen mirrored slms to use new version of pyglet. For now one can do
`pip install pyglet==1.5.27`

**Comment by ichristen** [comment]
@tpr0p , if you want to fix it, go for it, but I can tackle it in a week or so (along with the `pygletcamera` branch, commit 381af3ed4bf562bd1b6e7d249844ff88eebdda9f).

**Comment by ichristen** [comment]
I was lurking in slmpy's issues thread. If we get back to this, we should test other corner cases which have caused issues previously. In particular:

- Using multiple `ScreenMirrored` SLMs https://github.com/wavefrontshaping/slmPy/issues/6 / https://github.com/wavefrontshaping/slmPy/issues/8
- Testing at different resolutions https://github.com/wavefrontshaping/slmPy/issues/9

**Comment by ichristen** [comment]
Downgrading the pyglet version to 1.4.10 helped resolve a threading issue in #26 . In slmsuite v0.0.3, we should do the full upgrade to pyglet 2+.
