### ISSUE TITLE
MindVision

### ISSUE THREAD

**Issue by ichristen** [slmsuite/slmsuite#71]
@coldkevin1991 suggested implementing a `Camera` interface for MindVision hardware (see #57).

This would involve filling in the [abstract camera template](https://github.com/QPG-MIT/slmsuite/blob/main/slmsuite/hardware/cameras/template.py) with code from the grab.py in the provided [python_demo.zip](https://github.com/user-attachments/files/16191677/python_demo.zip). The mvsdk.py file would probably also be included in slmsuite as _mvsdk.py so the user does not need to copy this into the working directory.

We do not personally have MindVision hardware to test upon, so @coldkevin1991, it would be awesome if you could test (and implement the code if you feel comfortable with this).

Note that r0.0.2 makes some changes to `Camera` attributes, so working off of `dev` or after r0.0.2 is on `main` might be best.

**Comment by coldkevin1991** [comment]
[MindVision.zip](https://github.com/user-attachments/files/16250329/MindVision.zip)
Hi @ichristen, I have filled the camera template, but I am not sure all the function can work. 
I also have Holoeye SLM, later I will let them work together.

**Comment by ichristen** [comment]
Hi @coldkevin1991 ,

Sorry for my late reply.

I made some edits (mostly style) to your code. The main logic changes that I made was that the buffer will no longer be freed every `.get_image()` can and images are no longer saved (instead returned as a numpy array).

I have put your code on the `mindvision` branch with you as co-author. If you could test that branch (`git checkout mindvision` for a git installation) and make sure everything works on hardware, then we can clean up the code a bit more and pull things onto main. You should also feel free to make a fork of `slmsuite`, put your code on there, and then do a pull request from your fork.

Best,
Ian

**Comment by ichristen** [comment]
Hi @coldkevin1991 ,

The MindVision code is staged for the next release #85 .

I don't have MindVision hardware, so the current state is untested (and noted as such in the docs).

Additionally, the mvsdk.py file appears to be originally from [dddomodossola/nastroprint](https://github.com/dddomodossola/nastroprint/blob/master/mvsdk.py). Including this file into slmsuite would violate [nastroprint's Apache 2.0 license](https://github.com/dddomodossola/nastroprint/blob/master/LICENSE), so I instead documented the process for a user to download and include this python header file.

Best,
Ian

**Comment by coldkevin1991** [comment]
Hi @ichristen, 

The mvsdk.py file is originally from the official website:
https://www.mindvision.com.cn/category/software/demo-development-routine/
