### ISSUE TITLE
Potential issue in `get_farfield_spot_size`

### ISSUE THREAD

**Issue by Lufter** [slmsuite/slmsuite#79]
When implementing wavefront calibration with the superpixel method, in the current code we might get this error thrown

"ValueError: zero-size array to reduction operation maximum which has no identity" when the code gets to `find_centers` in cameraslm. By tracing this error across the entire package, we figured out it's due to and potential mishandling with the math in `FourierSLM/get_farfield_spot_size`.  We can see the program is trying to calculate the spot size according to our result, basically the M matrix from Fourier calibration. And it requires taking the square root of the determinant of M. As the following, `np.sqrt(np.linalg.det(M))`. But sometimes we do get a negative determinant from M, so `np.sqrt` freaks out. I wonder if this is done on purpose. Is it okay if I just say `np.sqrt(abs(np.linalg.det(M)))`, and it does seem to solve the problem?

**Comment by ichristen** [comment]
Hi @Lufter, thank you for catching this. I'm away from the computer now, but your solution sounds reasonable to fix `get_farfield_spot_size()`. Negative determinant was likely not caught in testing. I'll take a look at it later tonight and likely do a fix on the main branch.

**Comment by ichristen** [comment]
Sorry for the delay. Fixed in 282f97a9cc97cd72faef7b5beb7e6ff2c96ad9de . Pull request #80 pending. This issue will be closed once this is pulled.

Interestingly, `sqrt(abs(det(M)))` is used many times throughout the package (I searched for other breaking cases), but this was the only instance without the `abs`.
